# Generated by Django 4.1.2 on 2022-11-22 20:47

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, default='users/default.png', upload_to=app_users.models.user_media_path, verbose_name='profile photo'),
        ),
    ]
