# Generated by Django 4.1.2 on 2022-12-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('anon', 'Anonymous')], max_length=13, unique=True, verbose_name='role name'),
        ),
    ]
