# Generated by Django 4.1.2 on 2022-11-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycommercial',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories commercial info'},
        ),
    ]
