# Generated by Django 4.1.5 on 2023-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommercial',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(db_index=True, default='mg-smartfon-apple-iphone-13-pro-max-256gb-a2484-alpiiskii-zelenyi-1', max_length=512, unique=True, verbose_name='vendor code'),
            preserve_default=False,
        ),
    ]
