# Generated by Django 4.1.5 on 2023-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categorycommercial_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommercial',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.categorycommercial'),
        ),
    ]
