# Generated by Django 4.1.5 on 2023-01-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcommercial_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=1, verbose_name='the product specifications'),
            preserve_default=False,
        ),
    ]
