# Generated by Django 4.1.5 on 2023-01-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(null=True, verbose_name='the product specifications'),
        ),
    ]
