# Generated by Django 4.1.5 on 2023-01-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_category_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcommercial',
            old_name='category',
            new_name='categories',
        ),
    ]
