# Generated by Django 4.1.5 on 2023-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(verbose_name='the product specifications'),
        ),
    ]
