# Generated by Django 4.1.5 on 2023-01-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_category_productcommercial_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcommercial',
            old_name='categories',
            new_name='highlights',
        ),
    ]
