# Generated by Django 4.1.5 on 2023-01-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
    ]
