# Generated by Django 4.1.5 on 2023-01-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.JSONField(null=True, verbose_name='the product characters'),
        ),
    ]
