# Generated by Django 4.1.5 on 2023-01-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='characters',
        ),
    ]
