# Generated by Django 4.1.5 on 2023-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_product_product_characters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characters',
            new_name='specifications',
        ),
    ]
