# Generated by Django 4.1.5 on 2023-01-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productcommercial_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(null=True, verbose_name='the product specifications'),
        ),
    ]
