# Generated by Django 4.1.2 on 2022-11-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_current_config',
            field=models.BooleanField(default=False, help_text='Select if you want to use this config. Be sure that no one configs are not using now.', verbose_name='is current config'),
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='Config name'),
            preserve_default=False,
        ),
    ]
