# Generated by Django 4.1.2 on 2022-12-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_settings_is_current_config_settings_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
